### PR TITLE
Document URL Formatting in Readme

### PR DESCRIPTION
**Pull request by sbkn**
Nake URL format clearer, there must not be a traliling slash in configured URL

### CODE REVIEW

**Comment by Sunoo** [comment]
I don't believe I was aware of this, I guess I never tried adding the trailing slash. I'll do some testing this afternoon though.

I probably won't accept this PR though, as I'd greatly prefer to fix that instead of just document it.

**Comment by sbkn** [comment]
Currently it does not work with a trailing slash because you're concatenating a '/api/login' in line 83. That led to a failure to connect for me.

**Comment by sbkn** [comment]
You could try something like
```
          if(instance.url.endsWith('/')) {
            instance.url = instance.url.slice(0, -1);
          }
```
in  `didFinishLaunching()`

**Comment by Sunoo** [comment]
I have a plan, should be able to take care of it this afternoon.

**Comment by Sunoo** [comment]
I just did a quick test, and the double `/` worked fine for me? Can you share the error you were seeing?

**Comment by sbkn** [comment]
With trailing slash, e.g.:
```
        {
            "instances": [
                {
                    "name": "xxx",
                    "manufacturer": "Creality",
                    "model": "Ender 3 Pro",
                    "url": "http://xxxxxx.local/",
                    "api_key": "xxxxxx"
                }
            ],
            "name": "Octoprint Motion",
            "platform": "octoprint"
        }
```
Homebridge logs:
```
[21/02/2021, 15:48:43] [Octoprint Motion] xxx SockJS Connection Closed
```
and shows `0% Not Charging` for the printer.
Removing the trailing slash fixes it for me, it connects directly upon startup and displays the correct printing progress.

**Comment by Sunoo** [comment]
I have a fix in place, will be released after I do some more testing. Probably by tonight.

**Comment by Sunoo** [comment]
Fixed in v1.3.5

**Pull request closed without merging**
